[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "email-validator>=2.3.0",
    "flask-socketio>=5.5.1",
    "flask>=3.1.2",
    "flask-sqlalchemy>=3.1.1",
    "gunicorn>=23.0.0",
    "psycopg2-binary>=2.9.10",
    "requests>=2.32.5",
    "flask-dance>=7.1.0",
    "flask-login>=0.6.3",
    "oauthlib>=3.3.1",
    "pyjwt>=2.10.1",
    "stripe>=12.5.0",
    "werkzeug>=3.1.3",
    "gevent>=25.8.2",
    "openai>=1.104.0",
    "anthropic>=0.65.0",
    "numpy>=2.3.2",
    "pandas>=2.3.2",
    "flask-limiter>=3.12",
]
